# pytorch 入门
## 1.数据操作

In [1]:
import torch
import numpy as np

In [2]:
print(torch.__version__)

0.4.1


In [3]:
torch.cuda.is_available()

True

In [4]:
torch.version.cuda

'9.0'

创建一个5*3未初始化的tensor

In [5]:
x=torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [6]:
len(x.shape)

2

In [7]:
torch.tensor(x.shape).prod()

tensor(15)

In [8]:
x.numel()

15

创建随机初始化的tensor

In [9]:
x=torch.rand(5,3)
print(x)

tensor([[0.0440, 0.2937, 0.7630],
        [0.1280, 0.3114, 0.2310],
        [0.1084, 0.5834, 0.7364],
        [0.1330, 0.7379, 0.5651],
        [0.1724, 0.4510, 0.6530]])


In [10]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建

In [11]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [12]:
x=torch.ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [13]:
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[-1.8987, -1.5353, -1.7386],
        [-1.0769,  0.0494, -1.6781],
        [ 2.2850, -1.8700, -0.8867],
        [ 3.3948,  0.4815,  1.6588],
        [ 0.6903,  0.4139,  0.3746]])


In [14]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [15]:
print(x.numel())

15


In [16]:
x=x.reshape(3,5)
x

tensor([[-1.8987, -1.5353, -1.7386, -1.0769,  0.0494],
        [-1.6781,  2.2850, -1.8700, -0.8867,  3.3948],
        [ 0.4815,  1.6588,  0.6903,  0.4139,  0.3746]])

flatten初试

In [17]:
t1=torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
    ])
t2=torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
    ])
t3=torch.tensor([
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1],
    [1,1,1,1]
    ])
t=torch.stack((t1,t2,t3))
t.shape

torch.Size([3, 4, 4])

In [18]:
t

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]],

        [[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [19]:
#转换成CNN所使用tensor形式
t=t.reshape(3,1,4,4)#分别表示batchsize colorchannel length width
t

tensor([[[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]],


        [[[1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1],
          [1, 1, 1, 1]]]])

In [20]:
t[0]#first image

tensor([[[1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1],
         [1, 1, 1, 1]]])

In [21]:
t[0][0]#first channel in the first image

tensor([[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]])

In [22]:
t[0][0][0]#first row in the first channel 

tensor([1, 1, 1, 1])

In [23]:
t.flatten(start_dim=1).shape #需要将每张图片分别展开而不是一个batch全部展开 所以需要start_dim

torch.Size([3, 16])

In [24]:
t.flatten(start_dim=1)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## 2.数据运算

In [25]:
x = torch.tensor([1.0, 2, 4, 8])
# y = torch.tensor([2, 2, 2, 2])  dtype=torch.float64
#Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #3 'other'
y = torch.tensor([2, 2, 2, 2],dtype=torch.float32)
x,y

(tensor([1., 2., 4., 8.]), tensor([2., 2., 2., 2.]))

In [26]:
x.dtype,y.dtype

(torch.float32, torch.float32)

In [27]:
x + y, x - y, x * y, x / y, x ** y # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

同一种操作可以有很多种形式，以加法为例

In [28]:
#x+y已经展示过了
print(torch.add(x, y))
result=torch.empty(4)
torch.add(x, y,out=result)#指定输出
print(result)

tensor([ 3.,  4.,  6., 10.])
tensor([ 3.,  4.,  6., 10.])


In [29]:
#inplace 形式
y.add_(x)
print(y)
#PyTorch操作inplace版本都有后缀_, 例如x.copy_(y), x.t_()

tensor([ 3.,  4.,  6., 10.])


In [30]:
torch.exp(x)

tensor([   2.7183,    7.3891,   54.5981, 2980.9580])

以上是按元素操作

我们也可以把多个张量连结（concatenate）在⼀起，把它们端对端地叠起来形成⼀个更⼤的张量。我们只需要提供张量列表，并给出沿哪个轴连结。沿⾏（轴-0，形状的第⼀个元素）和按列（轴-1，形状的第⼆个元素）连结两个矩阵,第⼀个输出张量的轴-0⻓度（6）是两个输⼊张量轴-0⻓度的总和（3 + 3）；第⼆个输出张量的轴-1⻓度（8）是两个输⼊张量轴-1⻓度的总和（4 + 4）。

In [31]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [32]:
X==Y

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [33]:
X > Y

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [34]:
t=torch.tensor([
    [0,5,7],
    [6,0,7],
    [0,8,0]
    ],dtype=torch.float32)
t

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [35]:
print(t.eq(7))
print(t.ge(7))
print(t.le(7))
print(t.lt(7))
print(t.gt(7))

tensor([[0, 0, 1],
        [0, 0, 1],
        [0, 0, 0]], dtype=torch.uint8)
tensor([[0, 0, 1],
        [0, 0, 1],
        [0, 1, 0]], dtype=torch.uint8)
tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)
tensor([[1, 1, 0],
        [1, 1, 0],
        [1, 0, 1]], dtype=torch.uint8)
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 1, 0]], dtype=torch.uint8)


In [36]:
t <= torch.tensor( #等价
    np.broadcast_to(7,t.shape)
    ,dtype=torch.float32
    )

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 0, 1]], dtype=torch.uint8)

In [37]:
t.abs()

tensor([[0., 5., 7.],
        [6., 0., 7.],
        [0., 8., 0.]])

In [38]:
t.neg()

tensor([[-0., -5., -7.],
        [-6., -0., -7.],
        [-0., -8., -0.]])

In [40]:
t.sqrt()

tensor([[0.0000, 2.2361, 2.6458],
        [2.4495, 0.0000, 2.6458],
        [0.0000, 2.8284, 0.0000]])

In [ ]:
X.sum()
#对张量中的所有元素进⾏求和，会产⽣⼀个单元素张量。

tensor(66.)

## 3.广播机制

In [ ]:
t1=torch.tensor([
    [1,1],
    [1,1]
    ],dtype=torch.float32)
t2=torch.tensor([2,4],dtype=torch.float32)

In [ ]:
np.broadcast_to(t2.numpy(),t1.shape)

array([[2., 4.],
       [2., 4.]], dtype=float32)

In [ ]:
t1+t2

tensor([[3., 5.],
        [3., 5.]])

In [ ]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

在⼤多数情况下，我们将沿着数组中⻓度为1的轴进⾏⼴播
由于a和b分别是3 × 1和1 × 2矩阵，如果让它们相加，它们的形状不匹配。将两个矩阵⼴播为⼀个更⼤的3 × 2矩阵，如下所⽰：矩阵a将复制列，矩阵b将复制⾏，然后再按元素相加

In [ ]:
a+b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

## 4.索引和切片
和往常对numpy的操作相同

In [ ]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [ ]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [ ]:
X[1,2]

tensor(6.)

## 5.转其他类型

In [ ]:
A=X.numpy()
B=torch.tensor(A)

In [ ]:
type(A),type(B)

(numpy.ndarray, torch.Tensor)

In [ ]:
#要将⼤⼩为1的张量转换为Python标量，可以调⽤item函数或Python的内置函数
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)

## 6.数据预处理

In [ ]:
import os

os.makedirs(os.path.join('.', 'data'), exist_ok=True)
data_file = os.path.join('.', 'data', 'house_tiny.csv')
with open(data_file, 'w') as f:
    f.write('NumRooms,Alley,Price\n')  # 列名
    f.write('NA,Pave,127500\n')  # 每行表示一个数据样本
    f.write('2,NA,106000\n')
    f.write('4,NA,178100\n')
    f.write('NA,NA,140000\n')

In [ ]:
import pandas as pd

data=pd.read_csv('./data/house_tiny.csv')
data

NumRooms Alley   Price
0       NaN  Pave  127500
1       2.0   NaN  106000
2       4.0   NaN  178100
3       NaN   NaN  140000

In [ ]:
inputs,outputs=data.iloc[:,0:2],data.iloc[:,2]
inputs=inputs.fillna(inputs.mean())
print(inputs)

   NumRooms Alley
0       3.0  Pave
1       2.0   NaN
2       4.0   NaN
3       3.0   NaN


In [ ]:
inputs = pd.get_dummies(inputs,dummy_na=True)
print(inputs)

   NumRooms  Alley_Pave  Alley_nan
0       3.0           1          0
1       2.0           0          1
2       4.0           0          1
3       3.0           0          1


In [ ]:
X,y=torch.tensor(inputs.values),torch.tensor(outputs.values)
print(y.dtype)
X,y

torch.int64


(tensor([[3., 1., 0.],
         [2., 0., 1.],
         [4., 0., 1.],
         [3., 0., 1.]], dtype=torch.float64),
 tensor([127500, 106000, 178100, 140000]))

## 7.线性代数计算

In [ ]:
#标量   
x,y=torch.tensor(3.0),torch.tensor(2.0)
x,y

(tensor(3.), tensor(2.))

In [ ]:
#矩阵
A=torch.arange(20).reshape(5,4)
A

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]])

In [ ]:
A.t()  #不使用大写
print(A.dtype)

torch.int64


In [ ]:
#矩阵乘法
B = torch.ones(4, 3,dtype=torch.int64)
torch.mm(A, B)

tensor([[ 6,  6,  6],
        [22, 22, 22],
        [38, 38, 38],
        [54, 54, 54],
        [70, 70, 70]])

## 8.微积分