# pytorch 入门
## 1.数据操作

In [1]:
import torch

创建一个5*3未初始化的tensor

In [2]:
x=torch.empty(5,3)
print(x)

tensor([[5.7858e-39, 8.4490e-39, 5.3266e-39],
        [1.0286e-38, 9.3674e-39, 9.9184e-39],
        [8.4490e-39, 9.2755e-39, 1.0286e-38],
        [9.9184e-39, 8.9082e-39, 1.0102e-38],
        [1.0102e-38, 8.4490e-39, 4.2245e-39]])


创建随机初始化的tensor

In [3]:
x=torch.rand(5,3)
print(x)

tensor([[0.4458, 0.4591, 0.4710],
        [0.2080, 0.7505, 0.6428],
        [0.6780, 0.7076, 0.8248],
        [0.8814, 0.6691, 0.0160],
        [0.2844, 0.1186, 0.3126]])


In [5]:
x=torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


直接根据数据创建

In [7]:
x=torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
x=torch.ones(5,3,dtype=torch.float64)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [12]:
x=torch.randn_like(x,dtype=torch.float)
print(x)

tensor([[ 0.1963, -0.9936, -0.3318],
        [ 0.7765, -0.4794,  2.0868],
        [-0.1598, -0.8583,  1.3303],
        [-0.3711, -1.8212,  0.0137],
        [-1.6133, -0.7768, -0.6153]])


tensor的形状

In [13]:
print(x.shape)
print(x.size())

torch.Size([5, 3])
torch.Size([5, 3])


In [15]:
print(x.numel())

15


In [17]:
x=x.reshape(3,5)
x

tensor([[ 0.1963, -0.9936, -0.3318,  0.7765, -0.4794],
        [ 2.0868, -0.1598, -0.8583,  1.3303, -0.3711],
        [-1.8212,  0.0137, -1.6133, -0.7768, -0.6153]])

## 2.数据运算

In [28]:
x = torch.tensor([1.0, 2, 4, 8])
# y = torch.tensor([2, 2, 2, 2])  dtype=torch.float64
#Expected object of type torch.FloatTensor but found type torch.LongTensor for argument #3 'other'
y = torch.tensor([2, 2, 2, 2],dtype=torch.float32)
x,y

(tensor([1., 2., 4., 8.]), tensor([2., 2., 2., 2.]))

In [29]:
x.dtype,y.dtype

(torch.float32, torch.float32)

In [30]:
x + y, x - y, x * y, x / y, x ** y # **运算符是求幂运算

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

同一种操作可以有很多种形式，以加法为例

In [32]:
#x+y已经展示过了
print(torch.add(x, y))
result=torch.empty(4)
torch.add(x, y,out=result)#指定输出
print(result)

tensor([ 3.,  4.,  6., 10.])
tensor([ 3.,  4.,  6., 10.])


In [33]:
#inplace 形式
y.add_(x)
print(y)
#PyTorch操作inplace版本都有后缀_, 例如x.copy_(y), x.t_()

tensor([ 3.,  4.,  6., 10.])


In [34]:
torch.exp(x)

tensor([   2.7183,    7.3891,   54.5981, 2980.9580])

以上是按元素操作

我们也可以把多个张量连结（concatenate）在⼀起，把它们端对端地叠起来形成⼀个更⼤的张量。我们只需要提供张量列表，并给出沿哪个轴连结。沿⾏（轴-0，形状的第⼀个元素）和按列（轴-1，形状的第⼆个元素）连结两个矩阵,第⼀个输出张量的轴-0⻓度（6）是两个输⼊张量轴-0⻓度的总和（3 + 3）；第⼆个输出张量的轴-1⻓度（8）是两个输⼊张量轴-1⻓度的总和（4 + 4）。

In [35]:
X = torch.arange(12, dtype=torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [39]:
X==Y

tensor([[0, 1, 0, 1],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.uint8)

In [40]:
X > Y

tensor([[0, 0, 0, 0],
        [1, 1, 1, 1],
        [1, 1, 1, 1]], dtype=torch.uint8)

In [38]:
X.sum()
#对张量中的所有元素进⾏求和，会产⽣⼀个单元素张量。

tensor(66.)